# PostgreSQL Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/integration_db
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.sql-load-script=no-file

# Application
quarkus.application.name=integration
# OpenAPI / Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/q/openapi